name: Tests

on:
  push: { branches: [main] }
  pull_request: {}

env:
  CODECOV_TOKEN: '69cab0bb-8965-4f6e-8033-aa67540e6c28'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
      - name: Code conventions
        run: deno task lint
      - name: Unit/Integration tests
        run: deno task coverage
      - name: Upload coverage to Codecov
        run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
